CREATE  TABLE IF NOT EXISTS `bdsermeden`.`odontograma` (
  `idOdontograma` INT NOT NULL AUTO_INCREMENT ,
  `dni` VARCHAR(8) NOT NULL ,
  `d1` int NULL ,
  `d2` int NULL ,
  `d3` int NULL ,
  `d4` int NULL ,
  `d5` int NULL ,
  `d6` int NULL ,
  `d7` int NULL ,
  `d8` int NULL ,
  `d9` int NULL ,
  `d10` int NULL ,
  `d11` int NULL ,
  `d12` int NULL ,
  `d13` int NULL ,
  `d14` int NULL ,
  `d15` int NULL ,
  `d16` int NULL ,
  `d17` int NULL ,
  `d18` int NULL ,
  `d19` int NULL ,
  `d20` int NULL ,
  `d21` int NULL ,
  `d22` int NULL ,
  `d23` int NULL ,
  `d24` int NULL ,
  `d25` int NULL ,
  `d26` int NULL ,
  `d27` int NULL ,
  `d28` int NULL ,
  `d29` int NULL ,
  `d30` int NULL ,
  `d31` int NULL ,
  `d32` int NULL ,
  `fechareg` datetime DEFAULT NULL,
  PRIMARY KEY (`idOdontograma`) )
ENGINE = InnoDB